### PR TITLE
Add option to use a custom path inside an Azure Blob Storage Container

### PR DESCRIPTION
**Pull request by l0wl3vel**
## Summary

* Add optional Path field to CRD for the Azure backend
* Add a test
* Add documentation for the new field

### For Code changes

- [x] enhancement
- [x] PR contains the label `area:operator`
- [x] I have not made _any_ changes in the `charts/` directory.

### CODE REVIEW

**Comment by Kidswiss** [comment]
Hi @l0wl3vel 

Thanks for the contribution!

This looks sensible to me. I'll kick the e2e tests again, they are sometimes a by racy on github actions.

Once they pass I can approve and merge the change.

**Review by Kidswiss — APPROVED** [review]
LGTM

But before I merge, were you able to test this against an actual Azure bucket?

**Comment by l0wl3vel** [comment]
No, unfortunately not yet.

**Comment by l0wl3vel** [comment]
@Kidswiss This is now ready to merge.

**Comment by Kidswiss** [comment]
> And as an aside: Is there existing code to run e2e tests against real infrastructure? I am only aware of the local kind+minio e2e tests.

We currently only have the local minio/S3 tests automated.

**Pull request merged**
