### PR TITLE
Rework internal job queueing

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

Part 4 of a multi-PR code refactoring.

This PR focuses on integrating the "Executors" into the controllers themselves, so that they run in the same `context` and reconciliation loop. It has the following effect:
- The executor for each job type has been integrated into the controller
- There is no more separate Go routine running in the background (except the scheduler)
- (Integration) Testing just became way easier and less complex
- Removes the Prometheus metrics related to queue `k8up_jobs_queued_gauge`

Known Issues:
- Some functions and struct fields around `job.Config` can be optimizied/refactored/cleaned up as well. This could be done in a later PR.
- K8up logs don't reveal much of the internal flow. In a later PR, we might add several more info and debug statements, optionally also make use of Kubernetes Events.
- The new locking mechanism doesn't skip jobs. For example, given there is a schedule that backups every 30min, when the first backup takes 1.5h hours for some reason (e.g. backoff due to networking issues), the second and third backup are still scheduled. One might argue that the 2nd backup can be skipped completely since the first was still backing up, potentially be recent enough so the 2nd backup is irrelevant. This could to a never-ending congestion.
- During startup of K8up, there can still sometimes be a log entry about not being able to patch status conditions like "the object has been modified; please apply your changes to the latest version and try again". This can happen if both the Job controller and a backup controller modify the same resource at the same time. Not sure we can do something about it, unless we put the object itself also behind some kind of locking mechanism. However, in those cases the job controller should requeue the object for reconciliation and re-try a half-second later or so, this seems to be working good enough.

Resolved Issues:
- Cleanup of Backups mentioned in #789 works again.

Behaviour changes:
- K8up previously withheld an exclusive job execution based on the internal state called "observer". Now, it checks for actively running batch Jobs in Kubernetes instead. This means that K8up won't even spawn a Job object if another backup is running, this should be more reliable for Restic repository locking

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [x] PR contains the label `area:operator`
- [x] Link this PR to related issues
- [x] I have not made _any_ changes in the `charts/` directory.
- [x] Fix cleanup of old jobs
- [x] Replace Job executor/worker with simple listing and filtering, configure a backoff and conditions if exclusive job is running.

### CODE REVIEW

**Comment by ccremer** [comment]
Actually, I will rework the locking mechanism in this PR already. It avoids unnecessary discussions around this topic since a lot may change for this.
Resetting to draft. Sorry for the noise.

**Comment by ccremer** [comment]
The current locking mechanism seems to work:
```console
2023-01-09T10:46:00Z	DEBUG	k8up.operator.locker	Locked	{"controller": "prune.k8up.io", "namespace": "default", "name": "schedule-test-prune-hqrmj", "reconcileID": "1a1479cb-7ef0-4af4-b63d-1d4254c09ee0", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:46:00Z	DEBUG	k8up.operator.locker	Unlocked	{"controller": "prune.k8up.io", "namespace": "default", "name": "schedule-test-prune-hqrmj", "reconcileID": "1a1479cb-7ef0-4af4-b63d-1d4254c09ee0", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:46:48Z	INFO	k8up.operator	Job succeeded	{"controller": "job.k8up.io", "namespace": "default", "name": "backup-schedule-test-backup-jzqkb", "reconcileID": "2801f2c8-05f5-4783-994a-1b10ede0efaf"}
2023-01-09T10:47:00Z	INFO	k8up.operator	running schedule for	{"controller": "schedule.k8up.io", "namespace": "default", "name": "schedule-test", "reconcileID": "1078b9b3-32a0-47d8-b7c3-06e87cd2f11b", "job": "backup"}
2023-01-09T10:47:00Z	DEBUG	k8up.operator.locker	Locked	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "24c75c94-bc10-403e-9651-1431dc049fc4", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:47:00Z	DEBUG	k8up.operator.locker	Unlocked	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "24c75c94-bc10-403e-9651-1431dc049fc4", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:47:00Z	INFO	k8up.operator	Skipping job due to exclusivity or concurrency limit	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "24c75c94-bc10-403e-9651-1431dc049fc4"}
2023-01-09T10:47:18Z	INFO	k8up.operator	Job succeeded	{"controller": "job.k8up.io", "namespace": "default", "name": "prune-schedule-test-prune-hqrmj", "reconcileID": "d52717bc-8bc8-48f3-857b-ff0b110224bf"}
2023-01-09T10:47:30Z	DEBUG	k8up.operator.locker	Locked	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "6d1a06e1-d193-4661-9897-c984b8d886b5", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:47:30Z	INFO	k8up.operator	Listing all PVCs	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "6d1a06e1-d193-4661-9897-c984b8d886b5", "annotation": "k8up.io/backup"}
2023-01-09T10:47:30Z	DEBUG	k8up.operator.locker	Unlocked	{"controller": "backup.k8up.io",  "namespace": "default", "name": "schedule-test-backup-ckm4w", "reconcileID": "6d1a06e1-d193-4661-9897-c984b8d886b5", "repository": "s3:http://minio.minio:9000/k8up"}
2023-01-09T10:47:34Z	INFO	k8up.operator	Job succeeded	{"controller": "job.k8up.io", "namespace": "default", "name": "backup-schedule-test-backup-ckm4w", "reconcileID": "d84fe910-9c0c-4e8d-9a7d-427af788b611"}
```

**Comment by ccremer** [comment]
@Kidswiss 
I've discovered an issue with the locking mechanism:
The new locking mechanism doesn't skip jobs. For example, given there is a schedule that backups every 30min, when the first backup takes 1.5h hours for some reason (e.g. backoff due to networking issues), the second and third backup are still scheduled. One might argue that the 2nd backup can be skipped completely since the first was still backing up, potentially be recent enough so the 2nd backup is irrelevant. This could to a pile up a backlog of backups if the backup duration is often longer than the interval more often than not.

Is this an issue that is present in the current K8up also? I mean technically the user could specify an internal that is just lower than the backup duration already in today's K8up version.
Should I make it possible to skip redundant backups (or restores)? I was thinking to add a condition if a backup was skipped because another is running, and during reconciles check if there are other backups for the same repo in the same namespace and then only consider the newest backup resource. But might be large enough to justify its own PR.

**Comment by ccremer** [comment]
This PR is now ready to be discussed.

**Comment by ccremer** [comment]
> 

Okay, then I will not address this here as well.

**Comment by Kidswiss** [comment]
First off: generics!

The PR looks good to me. I'm curious if there are any measurable performance changes.

There was just one thing I didn't quite figure out:
What's the advantage of making `SetupWithManager` static?

**Review by Kidswiss — APPROVED** [review]

**Comment by ccremer** [comment]
> What's the advantage of making `SetupWithManager` static?

It's not that relevant for execution. I made it static so that we create the reconciler instances within the static function and initialize the fields in the respective packages, rather than in cmd/operator/main.go. Otherwise, the reconciler instance would have to be created first, before being able to use SetupWithManager, which is actually the "constructor" that initializes the fields.

Plus, it's more aligned to how Crossplane-based providers are set up, so I thought I'd create some familiarity for VSHNeers :)

**Comment by Kidswiss** [comment]
Something that just came to my mind: we can probably remove this alertrule, as the metrics don't exist anymore:

https://github.com/k8up-io/k8up/blob/master/config/samples/prometheus/rules.yaml#L26

**Comment by ccremer** [comment]
> Something that just came to my mind: we can probably remove this alertrule, as the metrics don't exist anymore:
> 
> https://github.com/k8up-io/k8up/blob/master/config/samples/prometheus/rules.yaml#L26

Right, I've made 2 new PRs for this: #794 and #795

**Pull request merged**
