### PR TITLE
Decrease the queue counter unconditionally

### LINKED ISSUE #751: Wrongly Decreasing the queued metric
### Description

During a debug session where a seemingly wrong `K8upJobStuck` alert kept appearing on a cluster, I found that if there are many backup jobs to the same repo, the likelyhood of wrong stuck alerts is a lot higher.

### Additional Context

Currently, the decrease is only called if there's no other job in the queue pointing to the same repository: https://github.com/k8up-io/k8up/blob/master/operator/queue/execution.go#L90

The `K8upJobStuck` check sees if there is a non-zero amount of jobs in the queue for more than 24h. This is to ensure that the operator is actually able to schedule the given jobs.

The way the logic is intended is, when a job is added to the queue https://github.com/k8up-io/k8up/blob/master/operator/queue/execution.go#L79, it increases the counter. When it leaves the queue it should decrease the counter https://github.com/k8up-io/k8up/blob/master/operator/queue/execution.go#L90. However the decrease is only triggered if there are no other jobs queued for the same repository.

The fix is to just move the decrease outside of that if case.

### Logs

```shell
Not applicable.
```

### Expected Behavior

The counter is always decreased when a job is fetched from the queue.

### Steps To Reproduce

1. Have schedules point to the same repository
2. The schedules trigger at the same time
3. Get the alert

### Version of K8up

v2.5.1

### Version of Kubernetes

any

### Distribution of Kubernetes

any

### PR DESCRIPTION
**Pull request by Kidswiss**
## Summary

Fixes #751

### For Code changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [x] PR contains the label `area:operator`
- [x] Link this PR to related issues
- [x] I have not made _any_ changes in the `charts/` directory.

### CODE REVIEW

**Review by ccremer — APPROVED** [review]

**Review by bastjan — APPROVED** [review]

**Comment by Kidswiss** [comment]
I've created a manual image for this branch and asked @haasad to test it on a cluster where we know that this issue happens regularly. Once I've got feedback I'll merge here.

**Comment by haasad** [comment]
I have this version running on one of the problematic clusters now, will observe for a few days and give feedback

**Comment by ccremer** [comment]
Merging to make a prerelease

**Comment by haasad** [comment]
@Kidswiss problem hasn't occurred anymore for a week now on a cluster running with the `ghcr.io/k8up-io/k8up:fix_decrease_queue` image, whereas it appeared every 2-3 days before

**Pull request merged**
